;;MIDI’|“àŠÖ”‚É‚æ‚é‰¹Šy‚ð‰‰‘tB

(import (normal kids))

(voice 95)
(tempo 240)
(volume 120)



(define (tak x y z n)
  (let ((esc '()))
    (define (tak1 x y z n)
      (chord (map tak->pitch (list x y z)) '(a (1 2 3 2 1 2 3 2)))
      (cond ((zero? n) (esc))
            ((<= x y) y)
            (else (tak1 (tak1 (- x 1) y z (- n 1))
                        (tak1 (- y 1) z x (- n 1))
                        (tak1 (- z 1) x y (- n 1))
                        (- n 1)))))
    (call/cc (lambda (c)
               (set! esc c) 
               (tak1 x y z n)))))

(define (tak->pitch n)
  (case n
    ((-1) 'D5)
    ((0) 'E5)
    ((1) 'F5)
    ((2) 'G5)
    ((3) 'A5)
    ((4) 'B5)
    ((5) 'C6)
    ((6) 'D6)
    ((7) 'E6)
    ((8) 'F6)
    ((9) 'G6)
    ((10) 'A6)
    ((11) 'B6)
    ((12) 'C7)))

(define (cde)
  (note 'C '(b 4))
  (note 'C# '(b -4))
  (note 'D '(b -4))
  (note 'D#)
  (note 'E)
  (note 'F)
  (note 'F#)
  (note 'G '(b -8))
  (note 'G#)
  (note 'A)
  (note 'A#)
  (note 'B '(b 1))
  (note 'C5 '(l 2) '(b -5)))