;;quasi-quote transfer
(define (quasi-transfer x n)
  (cond ((null? x) '())
        ((atom? x)
         (list 'quote x))
        ((and (pair? x)(eqv? (car x) 'quasiquote))
         (quasi-transfer (cadr x) (+ n 1)))
        ((and (pair? x)(eqv? (car x) 'unquote))
         (if (= n 0) 
             (cadr x))
             (quasi-transfer (cadr x) (- n 1))) 
        ((and (pair? x)(pair? (car x))(eqv? (caar x) 'unquote))
         (if (= n 0)
             (list 'cons (cadar x) (quasi-transfer (cdr x) n))
             (map (lambda (x1) (quasi-transfer x1 (- n 1))) x)))
        ((and (pair? x)(pair? (car x))(eqv? (caar x) 'unquote-splicing))
         (if (= n 0)
             (list 'append (cadar x) (quasi-transfer (cdr x) n))
             (map (lambda (x1) (quasi-transfer x1 (- n 1))) x)))
        (else
          (list 'cons (quasi-transfer (car x) n) (quasi-transfer (cdr x) n)))))